// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgAjjl6FpdBUGINGYmpJu7wj7NRQne4HM',
    appId: '1:980159136123:web:68fdb842daa316cc4f3dde',
    messagingSenderId: '980159136123',
    projectId: 'flutterchatapplication-eab94',
    authDomain: 'flutterchatapplication-eab94.firebaseapp.com',
    storageBucket: 'flutterchatapplication-eab94.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUbU7-tN_yBEbLJRpNXxQh7ACfZAsXFXM',
    appId: '1:980159136123:android:9357245f3b17f5234f3dde',
    messagingSenderId: '980159136123',
    projectId: 'flutterchatapplication-eab94',
    storageBucket: 'flutterchatapplication-eab94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7V_mUcfKQzlboHn_w4sZnsC3WiXORGZ0',
    appId: '1:980159136123:ios:69d3a2585b42e26f4f3dde',
    messagingSenderId: '980159136123',
    projectId: 'flutterchatapplication-eab94',
    storageBucket: 'flutterchatapplication-eab94.appspot.com',
    iosBundleId: 'com.example.chatMessengerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7V_mUcfKQzlboHn_w4sZnsC3WiXORGZ0',
    appId: '1:980159136123:ios:d73255185b2c22e04f3dde',
    messagingSenderId: '980159136123',
    projectId: 'flutterchatapplication-eab94',
    storageBucket: 'flutterchatapplication-eab94.appspot.com',
    iosBundleId: 'com.example.chatMessengerApp.RunnerTests',
  );
}
